# Dockerfile para o Banco de Dados MySQL
FROM mysql:8.0

# Define a codificação padrão para UTF-8
ENV MYSQL_CHARSET=utf8mb4 \
    MYSQL_COLLATION=utf8mb4_unicode_ci

# Copia o script SQL de inicialização para a pasta especial do MySQL.
# Qualquer script .sql nesta pasta é executado automaticamente na criação do container.
COPY ./sql.sql /docker-entrypoint-initdb.d/

# Exposição da porta padrão do MySQL
EXPOSE 3306
